#!/bin/bash -e

# Do we want to modify the config first with the script?
[ -f /etc/service/hubot/run.config ] && source /etc/service/hubot/run.config

# Is there any other script to run here?
[ -f /etc/service/hubot/run.initialization ] && source /etc/service/hubot/run.initialization

# configure properly environment
mkdir -p /etc/service/hubot/env
echo $HUBOT_HOME > /etc/service/hubot/env/HUBOT_HOME
echo $HUBOT_LOG > /etc/service/hubot/env/HUBOT_LOG
echo $HUBOT_NAME > /etc/service/hubot/env/HUBOT_NAME
echo $HUBOT_ADAPTER > /etc/service/hubot/env/HUBOT_ADAPTER
echo $HUBOT_DESC > /etc/service/hubot/env/HUBOT_DESC
echo $HUBOT_OWNER > /etc/service/hubot/env/HUBOT_OWNER
echo $HUBOT_JENKINS_URL > /etc/service/hubot/env/HUBOT_JENKINS_URL
echo $HUBOT_JENKINS_AUTH > /etc/service/hubot/env/HUBOT_JENKINS_AUTH
echo $HUBOT_GRAFANA_HOST > /etc/service/hubot/env/HUBOT_GRAFANA_HOST
echo $HUBOT_GRAFANA_API_KEY > /etc/service/hubot/env/HUBOT_GRAFANA_API_KEY
echo $HUBOT_GRAFANA_QUERY_TIME_RANGE > /etc/service/hubot/env/HUBOT_GRAFANA_QUERY_TIME_RANGE
echo $HUBOT_SLACK_TOKEN > /etc/service/hubot/env/HUBOT_SLACK_TOKEN
echo $HUBOT_SLACK_INCOMING_WEBHOOK > /etc/service/hubot/env/HUBOT_SLACK_INCOMING_WEBHOOK
echo $HUBOT_HOME > /etc/service/hubot/env/HOME
cd $HUBOT_HOME

export

exec chpst -u hubot:hubot -e /etc/service/hubot/env \
  $HUBOT_HOME/bin/hubot --name "$HUBOT_NAME" --adapter $HUBOT_ADAPTER 2>&1
