#!/bin/bash -e

# Do we want to modify the config first with the script?
[ -f /etc/service/hubot/run.config ] && source /etc/service/hubot/run.config

# Is there any other script to run here?
[ -f /etc/service/hubot/run.initialization ] && source /etc/service/hubot/run.initialization

# configure properly environment
mkdir -p /etc/service/hubot/env
echo $HUBOT_HOME > /etc/service/hubot/env/HOME

while IFS='=' read -r name value ; do
  if [[ $name =~ ^(HUBOT|NODE)_.* ]]; then
    echo "$name" ${!name}
    echo ${!name} > /etc/service/hubot/env/$name
  fi
done < <(env)

cd "$HUBOT_HOME"
exec chpst -u hubot:hubot -e /etc/service/hubot/env \
  $HUBOT_HOME/bin/hubot --name "$HUBOT_NAME" --adapter $HUBOT_ADAPTER 2>&1
